create table public.app_user (
  id bigint generated by default as identity primary key,
  auth_subject uuid unique references auth.users(id) on delete cascade,
  username varchar(80) not null unique,
  full_name varchar(120) not null,
  email varchar(254) not null unique,
  role varchar(20) not null default 'user' check (role in ('user', 'admin')),
  is_active boolean not null default true,
  session_version integer not null default 1 check (session_version > 0),
  password_hash varchar(255),
  security_question varchar(255),
  security_answer_hash varchar(255),
  profile_picture varchar(255),
  reset_token_hash varchar(255),
  reset_token_expires_at timestamp without time zone,
  password_changed_at timestamp without time zone,
  created_at timestamp without time zone not null default timezone('utc', now()),
  last_login timestamp without time zone
);

create table public.encrypted_file (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_user(id) on delete cascade,
  storage_name varchar(128) not null unique,
  filename varchar(255) not null,
  original_filename varchar(255) not null,
  algorithm varchar(20) not null check (algorithm in ('AES', 'Fernet', 'RSA')),
  file_size bigint not null check (file_size >= 0),
  is_text boolean not null default false,
  is_favorite boolean not null default false,
  created_at timestamp without time zone not null default timezone('utc', now())
);

create table public.activity_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.app_user(id) on delete set null,
  action varchar(100) not null,
  details text,
  target_type varchar(50),
  target_id varchar(128),
  success boolean not null default true,
  ip_address varchar(45),
  user_agent varchar(500),
  timestamp timestamp without time zone not null default timezone('utc', now())
);

create table public.shared_file (
  id bigint generated by default as identity primary key,
  encrypted_file_id bigint not null references public.encrypted_file(id) on delete cascade,
  shared_by_user_id bigint not null references public.app_user(id) on delete cascade,
  shared_with_user_id bigint not null references public.app_user(id) on delete cascade,
  permissions varchar(20) not null default 'read' check (permissions in ('read', 'download')),
  message text check (char_length(message) <= 1000),
  shared_at timestamp without time zone not null default timezone('utc', now()),
  expires_at timestamp without time zone,
  is_active boolean not null default true
);

create table public.download_token (
  id bigint generated by default as identity primary key,
  token_hash varchar(64) not null unique,
  user_id bigint not null references public.app_user(id) on delete cascade,
  storage_area varchar(20) not null check (storage_area in ('vault', 'temp', 'upload')),
  relative_name varchar(128) not null,
  download_name varchar(255) not null,
  expires_at timestamp without time zone not null,
  used_at timestamp without time zone,
  created_at timestamp without time zone not null default timezone('utc', now())
);

create table public.system_settings (
  id bigint generated by default as identity primary key,
  setting_name varchar(100) not null unique,
  setting_value text not null,
  updated_at timestamp without time zone not null default timezone('utc', now()),
  updated_by bigint references public.app_user(id) on delete set null
);

create unique index app_user_username_lower_uq on public.app_user (lower(username));
create unique index app_user_email_lower_uq on public.app_user (lower(email));
create index app_user_role_active_idx on public.app_user (role, is_active);
create index app_user_created_at_idx on public.app_user (created_at desc);
create index encrypted_file_user_created_idx on public.encrypted_file (user_id, created_at desc);
create index activity_log_user_time_idx on public.activity_log (user_id, timestamp desc);
create index activity_log_action_time_idx on public.activity_log (action, timestamp desc);
create unique index shared_file_one_recipient on public.shared_file (encrypted_file_id, shared_by_user_id, shared_with_user_id);
create index shared_file_recipient_idx on public.shared_file (shared_with_user_id, shared_at desc);
create index shared_file_sender_idx on public.shared_file (shared_by_user_id, shared_at desc);
create index download_token_user_expiry_idx on public.download_token (user_id, expires_at);

comment on table public.app_user is 'Server-owned CipherSphere identity mirror. The first Supabase identity is bootstrapped as administrator.';
comment on table public.encrypted_file is 'Metadata for authenticated CipherSphere envelopes; ciphertext remains in server-controlled storage.';
comment on table public.shared_file is 'Access grants for encrypted files. Encryption keys are never stored.';

alter table public.app_user enable row level security;
alter table public.encrypted_file enable row level security;
alter table public.activity_log enable row level security;
alter table public.shared_file enable row level security;
alter table public.download_token enable row level security;
alter table public.system_settings enable row level security;

revoke all on table public.app_user, public.encrypted_file, public.activity_log, public.shared_file, public.download_token, public.system_settings from anon, authenticated;
grant all on table public.app_user, public.encrypted_file, public.activity_log, public.shared_file, public.download_token, public.system_settings to service_role;

create or replace function public.ciphersphere_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  desired_username text;
  assigned_role text;
begin
  perform pg_advisory_xact_lock(20260713);

  desired_username := lower(regexp_replace(
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), split_part(new.email, '@', 1), 'user'),
    '[^a-zA-Z0-9_.-]+', '_', 'g'
  ));
  desired_username := left(trim(both '_' from desired_username), 70);
  if desired_username = '' then desired_username := 'user'; end if;
  if exists (select 1 from public.app_user where lower(username) = lower(desired_username)) then
    desired_username := desired_username || '_' || substr(new.id::text, 1, 8);
  end if;

  assigned_role := case
    when exists (select 1 from public.app_user where role = 'admin' and is_active) then 'user'
    else 'admin'
  end;

  insert into public.app_user (auth_subject, username, full_name, email, role, is_active)
  values (
    new.id,
    desired_username,
    left(coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), desired_username), 120),
    lower(new.email),
    assigned_role,
    true
  )
  on conflict (auth_subject) do update set
    email = excluded.email,
    full_name = excluded.full_name;
  return new;
end;
$function$;

revoke all on function public.ciphersphere_handle_new_auth_user() from public, anon, authenticated;
grant execute on function public.ciphersphere_handle_new_auth_user() to service_role;

create trigger on_auth_user_created_ciphersphere
after insert on auth.users
for each row execute function public.ciphersphere_handle_new_auth_user();
